// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fqmiviptxxvwftpozebd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZxbWl2aXB0eHh2d2Z0cG96ZWJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIyNTg4MTcsImV4cCI6MjA3NzgzNDgxN30.T7gEUbMJYxMAyl8uKphGrjkET3xorff_hn5KOSfe7dQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});